### ISSUE TITLE
Quoting a string that starts/ends with a single quote adds unnecessary extra single quotes

### ISSUE THREAD

**Issue by keysmashes** [rgov/node-shlex#15]
for example: `shlex.quote("'"))` results in `''"'"''` when it could just be `"'"`.

this is also how the original python shlex module behaves, though, so if you're aiming for bug-for-bug compatibility then this might be intended.

**Comment by rgov** [comment]
Nice catch. Relatedly, in `''` each gets quoted separately rather than as `"''"`. Do you have a proposal for an algorithm that generates the shortest quoted string? I prefer single-quoted strings `'foo'` in almost all cases because it avoids variable interpolation.

**Comment by keysmashes** [comment]
not off the top of my head, unfortunately. I agree that using single-quotes whenever possible is a good idea.

would it work to just delete all instances of two adjacent single quotes `''` after escaping the input string? that doesn't fix the other issue you point out, but it does at least improve it a bit (`''` would become `"'""'"` instead of `''"'"''"'"''`).
